### ISSUE TITLE
Shouldn't this loop deal with multiple input channels (as well as buses) ?

### ISSUE THREAD

**Issue by olilarkin** [webaudiomodules/api#5]
https://github.com/webaudiomodules/api/blob/f5bb2e7b1745621fa0b857020f5767cdc5b694f5/wamsdk/wam-processor.js#L70

**Comment by jariseon** [comment]
yes it should, thanks. needs to be reflected in this loop as well: https://github.com/webaudiomodules/api/blob/master/wamsdk/wam-processor.js#L153
